spring:
  main:
    web-application-type: none
  application:
    name: inventory-svc
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory_db
    username: inventory_user
    password: inventory_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect