apiVersion: v1
kind: Secret
metadata:
  name: orderservice-secret
  namespace: ecomerce
stringData:
  SPRING_DATASOURCE_USERNAME: order_user
  SPRING_DATASOURCE_PASSWORD: order_pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  namespace: ecomerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: orderservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://pg-order:5432/order_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: orderservice-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orderservice-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:29092
          volumeMounts:
            - name: orderservice-pvc
              mountPath: /data
      volumes:
        - name: orderservice-pvc
          persistentVolumeClaim:
            claimName: orderservice-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
  namespace: ecomerce
spec:
  selector:
    app: orderservice
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
