apiVersion: v1
kind: Secret
metadata:
  name: paymentservice-secret
  namespace: ecomerce
stringData:
  SPRING_DATASOURCE_USERNAME: payment_user
  SPRING_DATASOURCE_PASSWORD: payment_pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: ecomerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: paymentservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://pg-payment:5432/payment_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: paymentservice-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paymentservice-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:29092
          volumeMounts:
            - name: paymentservice-pvc
              mountPath: /data
      volumes:
        - name: paymentservice-pvc
          persistentVolumeClaim:
            claimName: paymentservice-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: ecomerce
spec:
  selector:
    app: paymentservice
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      

